// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbmigrate

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Follow struct {
	FollowingUserID pgtype.Int4      `json:"following_user_id"`
	FollowedUserID  pgtype.Int4      `json:"followed_user_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
}

type Post struct {
	ID    int32       `json:"id"`
	Title pgtype.Text `json:"title"`
	// Content of the post
	Body      pgtype.Text      `json:"body"`
	UserID    pgtype.Int4      `json:"user_id"`
	Status    pgtype.Text      `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Username string    `json:"username"`
	Role      string      `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
