// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dbmigrate

import (
	"context"
)

type Querier interface {
	CreateUsers(ctx context.Context, arg CreateUsersParams) (User, error)
	DeleteUsers(ctx context.Context, id int32) error
	GetUsers(ctx context.Context, id int32) (User, error)
	// -- name: GetAccountForUpdate :one
	// SELECT * FROM accounts
	// WHERE id = $1 LIMIT 1
	// FOR NO KEY UPDATE;
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUsers(ctx context.Context, arg UpdateUsersParams) (User, error)
}

var _ Querier = (*Queries)(nil)
